### ISSUE TITLE
Not working at boot

### ISSUE THREAD

**Issue by benoe77** [EmixamPP/linux-enable-ir-emitter#48] opened 2021-10-14 09:58 UTC
Even if I ran the "linux-enable-ir-emitter boot enable" command and the status is:

```
● linux-enable-ir-emitter.service - enable the infrared emitter
     Loaded: loaded (/lib/systemd/system/linux-enable-ir-emitter.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2021-10-14 08:28:01 CEST; 3h 24min ago
   Main PID: 1477 (code=exited, status=0/SUCCESS)

okt 14 08:28:01 user-linux systemd[1]: Starting enable the infrared emitter...
okt 14 08:28:01 user-linux systemd[1]: linux-enable-ir-emitter.service: Succeeded.
okt 14 08:28:01 user-linux systemd[1]: Finished enable the infrared emitter.
```

It just doesn't enable the emitter during face scan. I need to run the command again to make it work at the current session.
I'm on Ubuntu 20.4.3 LTS

**Comment by EmixamPP** [comment] 2021-10-14 10:04
Yes there is an issue on Ubuntu distro based I think. Someone has open the same issue the previous week. Please look at the wiki I've wrote a small fix. https://github.com/EmixamPP/linux-enable-ir-emitter/wiki/Issues.

But the problem is that I don't have a clean fix for this problem. In other words, this fix need to be done manually for each configuration.

**Comment by EmixamPP** [comment] 2021-10-14 16:23
> Even if I ran the "linux-enable-ir-emitter boot enable" command and the status is:
> 
> ```
>      Loaded: loaded (/lib/systemd/system/linux-enable-ir-emitter.service; enabled; vendor preset: enabled)
>      Active: inactive (dead) since Thu 2021-10-14 08:28:01 CEST; 3h 24min ago
>    Main PID: 1477 (code=exited, status=0/SUCCESS)
> 
> okt 14 08:28:01 user-linux systemd[1]: Starting enable the infrared emitter...
> okt 14 08:28:01 user-linux systemd[1]: linux-enable-ir-emitter.service: Succeeded.
> okt 14 08:28:01 user-linux systemd[1]: Finished enable the infrared emitter.
> ```
> 
> It just doesn't enable the emitter during face scan. I need to run the command again to make it work at the current session. I'm on Ubuntu 20.4.3 LTS

But in your first message I don't see `ExecStartPre=/sbin/modprobe uvcvideo (code=exited, status=0/SUCCESS)`.
Or did you mean that you had already applied the wiki fix before opening the issue ?

**Comment by benoe77** [comment] 2021-10-14 16:36
It seems to work on the latest version. Thanks.

**Comment by EmixamPP** [comment] 2021-11-04 09:52
https://github.com/EmixamPP/linux-enable-ir-emitter/issues/57#issuecomment-960600802

**Comment by EmixamPP** [comment] 2021-11-04 18:22
The release 3.2.2 is out and I think this will be resolve your problem.

**Comment by EmixamPP** [comment] 2021-11-06 16:58
https://github.com/EmixamPP/linux-enable-ir-emitter/issues/60#issuecomment-962477412 this comment means that this issue is also resolved ?

**Comment by benoe77** [comment] 2021-11-06 17:01
Even the previous version was working sometimes, sometimes wasn't. Let me test it for a few more days, then I will report back

**Comment by EmixamPP** [comment] 2021-11-15 09:56
The lastest version doens't modify the boot systemd (unfortunatly). 
When you said "usually after nightlong switched off states", you mean hibernate state ? Or a real shutdown ? 
An other issue have been open too for hibernate problem. (This hibernate feature isn't activate by default, right ?)

**Comment by benoe77** [comment] 2021-11-15 09:59
I mean a real shutdown.

**Comment by AndrejOrsula** [comment] 2021-11-20 23:45
I was having the same issue as described above. However, it *seems* to work on every boot after changing the type of the service to `forking`, i.e. `Type=forking` in `/usr/lib/systemd/system/linux-enable-ir-emitter.service`.

It is probably not an ideal solution, but it fixes some timing issue for me. With `oneshot`, my success rate was otherwise ~5%.

PS: Many thanks for the great work on this project.

**Comment by EmixamPP** [comment] 2021-11-22 18:48
May be these two sets of rules can fix your problem, execute :
1. `sudo mv /etc/udev/rules.d/99-linux-enable-ir-emitter.rules /etc/udev/rules.d/50-linux-enable-ir-emitter.rules`
2. Find in `lsusb` your camera device, for me it's `Bus 001 Device 002: ID 13d3:5406 IMC Networks Integrated Camera`
3. Note for the next step, the two values after `ID`
4. Replace my two values with yours in the following command and then execute : `echo 'ACTION=="add|change", ATTRS{idVendor}=="13d3", ATTRS{idProduct}=="5406", RUN+="/usr/bin/linux-enable-ir-emitter run"' | sudo tee -a /etc/udev/rules.d/50-linux-enable-ir-emitter.rules`
3. shutdown and start in order to test the solution

The idea of @AndrejOrsula shouldn't necessary in this case.

If someone of you can test it ? I hope I will a day find a solution which works on all Linux distribution :sweat_smile:

**Comment by benoe77** [comment] 2021-11-29 19:22
Currently testing this latest solution, seems all right so far.

**Closed** 2021-12-14 15:05 UTC
Labels: ubuntu

**Comment by nikfilippas** [comment] 2023-02-21 12:29
Changing to `Type=forking` from `Type=oneshot` as per @AndrejOrsula 's suggestion worked for me on XPS 9520 and Ubuntu 22.04 LTS.
